### ISSUE TITLE
connectors_with_custom_templates not working

### ISSUE THREAD

**Issue by saschbro** [prometheus-msteams/prometheus-msteams#102]
Hello together

We are using Docker Image 1.3.2 with `TEMPLATE_FILE` env referencing a custom alert card template. This works well for our handlers defined in the `connectors` section of our configuration file. Because I want to connect other channels with another card style than our default one I added a `connectors_with_custom_templates` section to our configuration file as described in the readme (https://github.com/prometheus-msteams/prometheus-msteams#customise-messages-per-ms-teams-channel). Unfortunately, the template referenced by the `TEMPLATE_FILE` env is always used instead the custom one specified for the handler in `connectors_with_custom_templates`.

I checked the code and it looks like in `main.go` line 226 the wrong template file is used!? However, I have no experience with Go.

**Comment by bzon** [comment]
Hi @saschbro, I understand your problem. Can I see your YAML file so I can use it for testing? Please redact the webhook urls.

**Comment by bzon** [comment]
@saschbro this will be fixed in the next release.

**Comment by bzon** [comment]
@saschbro please now use https://github.com/prometheus-msteams/prometheus-msteams/releases/tag/v1.3.3

Github automatically closed the issue. 😒

**Comment by saschbro** [comment]
Hi @bzon. Thank you very much for your fast reply and the fix. I tested with version 1.3.3 and it's working as expected now. Not sure if you still need the configuration file:
```
connectors:
  - teams_monitoring: https://outlook.office.com/webhook/...
  - teams_prod_monitoring: https://outlook.office.com/webhook/...
  - teams_inte_monitoring: https://outlook.office.com/webhook/...

connectors_with_custom_templates:
  - request_path: /teams_acme
    template_file: ./acme-message-card.tmpl
    webhook_url: https://outlook.office.com/webhook/...
    escape_underscores: true
```
Thanks again for the quick support!
