### ISSUE TITLE
[FEATURE] Disable Grouping for Alerts

### ISSUE THREAD

**Issue by shibumi** [prometheus-msteams/prometheus-msteams#118]
**Is your feature request related to a problem? Please describe.**
Right now an alert notification looks like this:
![msteams alert](https://lapee79.github.io/en/article/prometheus-alertmanager-with-msteams/teams-alert-message.png)

I would like to have a notification for every single alert and the alert message in the title instead of "Prometheus Alert (fired)". The notification changes the color already, I think this is enough for seeing if it's an active alert or a "resolved" message.

Sadly, the Alertmanager does not support *not grouping*, so we need a nice way to configure this in the msteams receiver, I guess?

I had a look on the card template, it should be trivial to change it for single alerts, but how would I disable grouping?

**Describe the solution you'd like**

I would like to have the alert message in the title of the notification card and in every notification card only *one* alert.

**Describe alternatives you've considered**
I tried changing the card template, until I realized that every card can have multiple alerts.

**Additional context**

Maybe it's possible to group by alert message in the alerting manager?

**Comment by bzon** [comment]
Thanks for raising this feature request. @Knappek is currently working on refactoring the existing card templating code. We will see if this is something that we can consider as a configurable option.

**Comment by shibumi** [comment]
Just an idea, but couldn't we just group by the alert message or alert name? We would still have a group of alerts, but at least the 'meaning' of the alerts would be the same.

**Comment by Knappek** [comment]
Valid point @shibumi. While refactoring I'll keep your suggestions in mind and will come back to you in case of questions.

**Comment by Knappek** [comment]
Hey @shibumi in #114 we will introduce a new flag `-disable-grouping` which will simply allow you to send one message for each alert.

> Just an idea, but couldn't we just group by the alert message or alert name? We would still have a group of alerts, but at least the 'meaning' of the alerts would be the same.
Can you elaborate on this a little bit more please? Do you have an idea how to do this as I don't know how we would define the "meaning" of certain alerts...based on what condition?

**Comment by shibumi** [comment]
Hi @Knappek My idea was just to group on `alert names`. So if you have an alert that is called `Persistent Volume out of storage`, all alerts with the same name will group on that one. This would be configured on alertmanager side, it has nothing to do with prometheus-msteams.

I've just heard that it's possible to disable grouping in alertmanager via `group_by: [...]` (triple dots). Did anyone try this? I think, this would solve this issue here.

**Comment by Knappek** [comment]
@shibumi , yes I can confirm that. You can easily reproduce it as explained in [the readme](https://github.com/prometheus-msteams/prometheus-msteams#setting-up-prometheus-alert-manager) using [dockprom](https://github.com/stefanprodan/dockprom). 

Simply add prometheus-msteams to docker-compose.yml 

```yaml
  promteams:
    image: promteams
    container_name: promteams
    environment: 
      - TEAMS_INCOMING_WEBHOOK_URL=https://outlook.office.com/webhook/xxxxx
      - TEAMS_REQUEST_URI=alertmanager
    ports:
      - 2000:2000
    networks:
      - monitor-net
```

and use the following `alertmanager/config.yml` :

```yaml
route:
  group_by: [...]
  group_interval: 30s
  repeat_interval: 30s
  group_wait: 30s
  receiver: 'prometheus-msteams'

receivers:
- name: 'prometheus-msteams'
  webhook_configs:
  - send_resolved: true
    url: 'http://promteams:2000/alertmanager' # the prometheus-msteams proxy
```
