### ISSUE TITLE
Customising the alert fields shown

### ISSUE THREAD

**Issue by callahan22** [prometheus-msteams/prometheus-msteams#133]
Pretty sure this isn't a bug but it's also not a feature request so I'm dropping this here.

**Version**
Running the latest prometheus-msteams and the latest version of docker

***Problem***
I'm struggling to get only the fields I want in the alert within Teams. I know I'm missing something but I can't see what. I'd like to control the contents of the alert. I only want minimal info yet I've getting all the component parts such as objectname, job, etc.

Here's my config:

alert-rules.yml
```
- name: '5% C: drive space'
  rules:
  - alert: 'Drive C: has less than 5% remaining space'
    expr: win_disk_Percent_Free_Space{exported_instance="C:",job="test_job"} < 5
    for: 10m
    labels:
      severity: warning
    annotations:
#      title: "{{ $labels.host }} - Disk Space warning"
#      summary: "{{ $labels.host }} ({{ $labels.type }}) - Location: {{ $labels.job }} - Less than 5% of free space remaining on system drive."
```

alertmanager.yml
```
global:
  resolve_timeout: 5m

# Files from which custom notification template definitions are read.
# The last component may use a wildcard matcher, e.g. 'templates/*.tmpl'.
#  templates:
#    [ - <filepath> ... ]

route:
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 10m
  group_by: ['name', 'alertname']
  receiver: 'default-receiver'

  #////////////////////////////////////////////////////////////////#
  #-------------------> RECEIVER DEFINITIONS <---------------------#
  #////////////////////////////////////////////////////////////////#
receivers:
  - name: 'default-receiver'
    webhook_configs:
      - send_resolved: true
        url: 'http://promteams:2000/default_channel'
```

promteams-config.yml
```
connectors:
  - default_channel: "<MSTEAMS_WEBHOOK>"
    escape_underscores: true # get the effect of -auto-escape-underscores.
```

docker-compose section
```
  promteams:
    image: bzon/prometheus-msteams:latest
    container_name: promteams
    restart: unless-stopped
    volumes:
      - ./promteams/config.yml:/etc/config.yml
      - ./promteams/templates:/home
    environment:
      - CONFIG_FILE=/etc/config.yml
      - TEMPLATE_FILE=/home/card-with-silence-action.tmpl
```

My alerts contain the fields:
alertname
exported\_instance
host
instance
job
name
objectname
severity
type

I only want some of these but I'm struggling to see how to remove them. I'm looking at the template as that is where I would assume I would make alterations but obviously missing something obvious.

Any pointers appreciated.
