### ISSUE TITLE
[FEATURE] Teams channel configured through url

### ISSUE THREAD

**Issue by kbudde** [prometheus-msteams/prometheus-msteams#178]
**Is your feature request related to a problem? Please describe.**
At the moment I have to configure the teams webhooks in two places:
- prometheus-msteams
- alertmanager

Running msteams in docker only allows one webhook (correct)? 
So I either install two container or I build the container "myself" with configuration.

Adding a channel always requires changing both.

**Describe the solution you'd like**
it would be really helpfull to have a special webhook path for msteams, like:
http://prometheus-msteams:2000/_by-path/xxxx/aaa/bbb

This endpoint should use the webhook:
https://outlook.office.com/webhook/xxxx/aaa/bbb

As a result I can configure all teams channels in alertmanager only.

Alertmanager config:
```
receivers:
- name: 'prometheus-msteams-ops'
  webhook_configs: # https://prometheus.io/docs/alerting/configuration/#webhook_config 
  - send_resolved: true
    url: 'http://localhost:2000/_by-path/xxxx/aaa/bbb' # the prometheus-msteams proxy
- name: 'prometheus-msteams-db'
  webhook_configs: # https://prometheus.io/docs/alerting/configuration/#webhook_config 
  - send_resolved: true
    url: 'http://localhost:2000/_by-path/XXXX2/AAA2/BBB2' 
....
```

**Additional context**
There is a "similiar" pull request open #83 but this enforces to use labels for receivers which doesn't work in all cases.

I can provide a pull request implementing described behavior if you want.
