### ISSUE TITLE
yaml: unmarshal errors: line 2: cannot unmarshal !!map into []map[string]string [BUG]

### ISSUE THREAD

**Issue by nicomontes** [prometheus-msteams/prometheus-msteams#189]
**Describe the bug**
I reveive this error in pod when i run helm chart :
`{"caller":"main.go:148","err":"yaml: unmarshal errors:\n  line 2: cannot unmarshal !!map into []map[string]string","ts":"2021-03-05T10:57:36.384000665Z"}`

**Version**
1.4.1

**config**
```yaml
---
image:
  repository: quay.io/prometheusmsteams/prometheus-msteams
  tag: v1.4.1
connectors: 
  alertmanager: "https://webhook.office.com/webhookb2/xxx/IncomingWebhook/xxx"
container: 
  additionalArgs: 
    - -debug
```
