### ISSUE TITLE
[BUG] Disabling debug logging doesn't work in v1.4.2

### ISSUE THREAD

**Issue by kotchaosu** [prometheus-msteams/prometheus-msteams#191]
**Describe the bug**

Deployed prometheus-msteams helm chart in version 1.4.1 with Docker image v1.4.2. Tried to disable logging of debug messages, but still getting then:

```
2021/03/12 16:20:20 [DEBUG] POST <connector_url>
```

Tried setting debug to false via container args:

```
# snippet from k8s deployment
spec:
  template:
    spec:
      containers:
      - args:
        - -config-file=/etc/config/connectors.yaml
        - -template-file=/etc/template/card.tmpl
        - -debug=false
        name: prometheus-msteams
```

also via env vars:

```
# snippet from k8s deployment
spec:
  template:
    spec:
      containers:
        - name: prometheus-msteams
          env:
            - name: DEBUG
              value: "false"
```

In both ways it doesn't work.

**Version**

Docker image v1.4.2

**Expected behavior**

Debug log messages are dropped when passing `-debug=false` via args or `DEBUG=false` via env vars.
