### ISSUE TITLE
[BUG] Unable to inflate Helm chart using helmChartInflationGenerator and Kustomize

### ISSUE THREAD

**Issue by sebas-w** [prometheus-msteams/prometheus-msteams#194]
**Describe the bug**
Inflation of helm chart via helmChartInflationGenerator and Kustomize fails due to error caused by a duplicate key `imagePullPolicy` on the deployment itself.

**Version**
Latest version

**To Reproduce**

1. Create the Kustomization File:

  ```yaml
  apiVersion: kustomize.config.k8s.io/v1beta1
  kind: Kustomization
  helmChartInflationGenerator:
    - chartName: prometheus-msteams
      chartRepoUrl: https://prometheus-msteams.github.io/prometheus-msteams/
      values: values.yaml
      releaseName: prometheus-msteams
      releaseNamespace: solar-system
  ```

2. Use a valid Values.yaml file:

```yaml
---
replicaCount: 1

image:
  repository: quay.io/prometheusmsteams/prometheus-msteams
  tag: v1.4.1
  pullPolicy: Always

imagePullSecrets: []

extraEnvs: {}

container:
  port: 2000
  additionalArgs: []

resources:
  limits:
    cpu: 10m
    memory: 32Mi
  requests:
    cpu: 1m
    memory: 8Mi

service:
  type: ClusterIP
  port: 2000

nodeSelector: {}

tolerations: []

affinity: {}

podSecurityContext:
  runAsUser: 1000
  runAsNonRoot: true

priorityClassName: ""

# Custom labels for pod assignment
podLabels: 
  namespace: test-system

metrics:
  serviceMonitor:
    enabled: true
    additionalLabels: {}
    scrapeInterval: 30s

## Specify the custom message card template for MS teams
customCardTemplate: ""
# customCardTemplate: |
#   {{ define "teams.card" }}
#   {...}
#   {{ end }}

connectors:
- default: https://valid.webhook.link

# ref: https://github.com/prometheus-msteams/prometheus-msteams#customise-messages-per-ms-teams-channel
connectorsWithCustomTemplates: []
# - request_path: /alert2
#   template_file: |
#     {{ define "teams.card" }}
#     {...}
#     {{ end }}
#   webhook_url: <webhook>
#   escape_underscores: true

# Env from existing secrets or configmaps (in same namespace), will passed through to contains 'envFrom'
envFrom: {}
# envFrom:
#   - secretRef:
#       name: my-prometheus-msteams-env-secret
#   - configMapRef:
#       name: my-prometheus-msteams-env-cm
```

3. Run `kustomize build .` in the directory with your kustomization.yaml and values.yaml file

**Expected behavior**
Kustomize should be able to inflate the helm chart without issue as I can manually.

**Actual Behavior**

```bash
❯ kustomize build .                                                                                         
2021/03/22 16:02:07 failed to decode ynode: yaml: unmarshal errors:
  line 47: mapping key "imagePullPolicy" already defined at line 37
```

⚠️**ROOT CAUSE**⚠️
This is due to the following duplicated key: 

https://github.com/prometheus-msteams/prometheus-msteams/blob/f6a58c95573ea7f530aa12ac7243dacf3c05ba40/chart/prometheus-msteams/templates/deployment.yaml#L45

Removing the key will resolve the error.
