### ISSUE TITLE
Container has the same liveness and readiness probe

### ISSUE THREAD

**Issue by psibi** [prometheus-msteams/prometheus-msteams#211]
**Describe the bug**

Right now the deployment yaml (from the helm chart) has the same liveness and readiness probe:

```yaml
          readinessProbe:
            httpGet:
              path: /config
              port: http
            initialDelaySeconds: 1
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /config
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
```

Using a static tool like [kube-score](https://github.com/zegl/kube-score) throws this error:

```
apps/v1/Deployment prometheus-msteams in my-namespace                       💥
    [CRITICAL] Pod Probes
        · Container has the same readiness and liveness probe
            Using the same probe for liveness and readiness is very likely
            dangerous. Generally it's better to avoid the livenessProbe than
            re-using the readinessProbe.
            More information: https://github.com/zegl/kube-score/blob/master/README_PROBES.md
```

**Version**

```
      containers:
        - name: prometheus-msteams
          image: "quay.io/prometheusmsteams/prometheus-msteams:v1.4.1"
```

**To Reproduce**

Use the manifest generated by latest helm chart and pass it to `kube-score` will result in such an error pasted above.

**Expected behavior**

Liveness probe and readiness probe should be different. There are some recommendations here: https://github.com/zegl/kube-score/blob/master/README_PROBES.md#livenessprobe

**Additional context**

No additional context, but can provide if something is required.
