### ISSUE TITLE
[FEATURE] Message card flexibility. How to access job name parameter?

### ISSUE THREAD

**Issue by alfador1** [prometheus-msteams/prometheus-msteams#215]
**Is your feature request related to a problem? Please describe.**
Hello guys,
It maybe more like an exploration question then an issue.
So I night your advice on it. I tried to contact you through microsoft teams channel in "Contribution page", but alas I couldn't.

So basically on the topic.
I'm trying to access the job_name field in the message cards, but I cannot seem to get how that to happen.
I need to have a condition "if job_name" is blackbox " do one description, else go with the default one.
How do you also access instance name (hostname) for example?
The documentation in message is not clear for to understand.

**Describe the solution you'd like**
I need a way simpler approach to his message card:
https://github.com/prometheus-msteams/prometheus-msteams/blob/master/examples/templates/default-message-card.tmpl

![image](https://user-images.githubusercontent.com/35370751/124751475-f5c4d180-df26-11eb-9243-b524b7838df7.png)

Instead of "Prometheus Firing" get "Instance is down", or Instance is UP. That will be based on the job name (which I can't seem to get how to access.

I've tried to do this rule:
[    "title": "{{- if eq .labels.job "blackbox" -}}
             {{.CommonLabels.alertname }} is DOWN
             {{- else -}}
             Prometheus Alert ({{ .Status | title }})
             {{- end -}}",
](url)
Doesn't really work as expected 
And I don't want all those "severity, pod, instance. Only description and alarm name.

**Comment by Knappek** [comment]
Hi @alfador1, `.labels.job` does not exist at a global scope but only at the `Alert` level and with capital `L`. See the [Prometheus Alertmanager Notification template reference](https://prometheus.io/docs/alerting/latest/notifications/) for further information.

**Comment by alfador1** [comment]
@Knappek So as of your example it should be "title": "{{- if eq .$alert.Labels. $job "blackbox" -}}. if I understand right?

**Comment by Knappek** [comment]
`.Alerts` is an array, see the following example request:

```yaml
{
  "version": "4",
  "groupKey": "{}:{alertname=\"high_memory_load\"}",
  "status": "firing",
  "receiver": "teams_proxy",
  "groupLabels": {
      "alertname": "high_memory_load"
  },
  "commonLabels": {
      "alertname": "high_memory_load",
      "monitor": "master",
      "severity": "warning"
  },
  "commonAnnotations": {
      "summary": "Prometheus Test",
      "runbook": "https://github.com/bzon/prometheus-msteams"
  },
  "externalURL": "http://docker.for.mac.host.internal:9093",
  "alerts": [
      {
          "labels": {
              "alertname": "high_memory_load",
              "instance": "instance-with-hyphen_and_underscore",
              "job": "docker_nodes",
              "monitor": "master",
              "severity": "warning"
          },
          "annotations": {
              "description": "10.80.40.11 reported high memory usage with 23.28%.",
              "summary": "Server High Memory usage"
          },
          "startsAt": "2018-03-07T06:33:21.873077559-05:00",
          "endsAt": "0001-01-01T00:00:00Z"
      }
  ]
}
```

So one Prometheus alert can contain multiple `alerts`. Hence, there is no 1-to-1 relationship between your the `title` and the job name of one of the alerts.

Anyway, if you are still trying to have a conditional title based on the first alerts job name, you could use the following template, which is basically the same as the default template but having the conditional title that you request:

```
{{ define "teams.card" }}
{
  "@type": "MessageCard",
  "@context": "http://schema.org/extensions",
  "themeColor": "{{- if eq .Status "resolved" -}}2DC72D
                 {{- else if eq .Status "firing" -}}
                    {{- if eq .CommonLabels.severity "critical" -}}8C1A1A
                    {{- else if eq .CommonLabels.severity "warning" -}}FFA500
                    {{- else -}}808080{{- end -}}
                 {{- else -}}808080{{- end -}}",
  "summary": "{{- if eq .CommonAnnotations.summary "" -}}
                  {{- if eq .CommonAnnotations.message "" -}}
                    {{- if eq .CommonLabels.alertname "" -}}
                      Prometheus Alert
                    {{- else -}}
                      {{- .CommonLabels.alertname -}}
                    {{- end -}}
                  {{- else -}}
                    {{- .CommonAnnotations.message -}}
                  {{- end -}}
              {{- else -}}
                  {{- .CommonAnnotations.summary -}}
              {{- end -}}",
  "title": "{{- if eq (index .Alerts 0).Labels.job "blackbox" -}}
            {{.CommonLabels.alertname }} is DOWN
            {{- else -}}
            Prometheus Alert ({{ .Status | title }})
            {{- end -}}",
  "sections": [ {{$externalUrl := .ExternalURL}}
  {{- range $index, $alert := .Alerts }}{{- if $index }},{{- end }}
    {
      "activityTitle": "[{{ $alert.Annotations.description }}]({{ $externalUrl }})",
      "facts": [
        {{- range $key, $value := $alert.Annotations }}
        {
          {{- if ne $key "description" -}}
            "name": "{{ $key }}",
            "value": "{{ $value }}"
          {{- end -}}
        },
        {{- end -}}
        {{$c := counter}}{{ range $key, $value := $alert.Labels }}{{if call $c}},{{ end }}
        {
          "name": "{{ $key }}",
          "value": "{{ $value }}"
        }
        {{- end }}
      ],
      "markdown": true
    }
    {{- end }}
  ]
}
{{ end }}
```

Hope this helps. Feel free to close the issue if so.
