### ISSUE TITLE
Docker default config.yml example

### ISSUE THREAD

**Issue by cbryant42** [prometheus-msteams/prometheus-msteams#228]
Hi, I wasn't sure where to post this to, so feel free to remove if this isn't the place, but I wanted to know if there was documentation around the syntax for a Docker yml file to build from. My use case dictates using a .yml file to build and deploy to an existing stack, but I can't seem to get this method to work, but I can get it to work using the docker run ... command given in the README. 

My current prometheus-msteams.yml file looks like this:
```
version: '3.5'
services:
    prometheus-msteams:
        image: bzon/prometheus-msteams:latest
        environment:
            - TEAMS_INCOMING_WEBHOOK_URL="{webhook}"
            - TEAMS_REQUEST_URI="alertmanager"
```

When I install with the README docker run command, everything works fine:
```
docker run -d -p 2000:2000 --name="promteams" -e TEAMS_INCOMING_WEBHOOK_URL="{webhook}" -e PROMTEAMS_DEBUG="true" -e TEAMS_REQUEST_URI="alertmanager" bzon/prometheus-msteams:latest
```

Can someone help me recreate the default config.yml file, or point me to an example?

**Comment by cbryant42** [comment]
I was able to figure it out on my own! It seems ports still need to be specified even if using the default "2000:2000", and **do not** use "" around the environment variable definitions.  
Here is the final prometheus-msteams.yml I'm using for reference:

```
version: '3.5'
services:
    prometheus-msteams:
        image: bzon/prometheus-msteams:latest
        environment:
          - TEAMS_INCOMING_WEBHOOK_URL={your_webhook}
          - TEAMS_REQUEST_URI=alertmanager
        ports:
          - "2000:2000"
```

I still think sharing a template for a Docker specific config.yml file would be very helpful for future users.
