### ISSUE TITLE
[BUG] Escaping of labels goes wrong

### ISSUE THREAD

**Issue by GreenRover** [prometheus-msteams/prometheus-msteams#243]
**Describe the bug**
I a label contains "_" underline it will be false positively escaped:
![image](https://user-images.githubusercontent.com/512850/150762714-cbd282bb-77c0-4692-8c0b-6afd1b123a61.png)

This leads in my case to:
The visible text have a \ to much in the url that is contain in the solving label/annotation.

And the link contains a %5c (encoded /) to much witch make the link broken.

Alertmanager gui and e-mail notifications dont show this issue.

**Version**
prometheus-msteams: v1.5.0
alertmanager: v0.21.0
prometheus: v2.31.1

**To Reproduce**
Have an prometheus rule like:
```
- name: PEngTargetsMemory
  rules:
  - alert: PEngTargetsNetwork:targets_infrastructure_server_upload
    expr: (rate(node_network_transmit_bytes_total{host=~"rcs(infra|bs).*", device="eth0"}[10m])) > 1000000
    for: 20m
    labels:
      severity: "AlertMedium"
      receiver: "PengTeams"
      time_window: "6to21"
    annotations:
      summary: "The network load over the last 10 minutes was above 1MB per second. Host: {{ $labels.host }} )"
      description: "network load (upload) at 1MB"
      solving: "recommended: Check https://grafana-rcs.sbb-cloud.net/d/infra_os_health/peng-infrastructure-os-health?var-node={{ $labels.host }}"
```

**Expected behavior**
No not necessary escaping or broken urls.
