### ISSUE TITLE
Get connector webhook URLs from a secret as an alternative to passing as a value

### ISSUE THREAD

**Issue by bkrein-vertex** [prometheus-msteams/prometheus-msteams#244]
I would like to be able to use secrets for my webhook URLs rather than pass them as values to the Helm chart.  We store the webhook URLs in AWS Secrets Manager & would like to be able to use those values via the [Secrets Store CSI](https://secrets-store-csi-driver.sigs.k8s.io/).

**Comment by bitnik** [comment]
Hi @bkrein-vertex, today I found out how to do it with the current chart.

You should create a secret for `TEAMS_INCOMING_WEBHOOK_URL` env variable and then use `values.envFrom` to pass it to the pod as env variable. Here is an example:

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: ms-teams-webhook
  namespace: monitoring
type: Opaque
data:
  TEAMS_INCOMING_WEBHOOK_URL: "<base64-encoded-webhook-url>"
  TEAMS_REQUEST_URI: "<base64-encoded-path>"
```

and then in your chart config include:

```yaml
envFrom:
  - secretRef:
      name: ms-teams-webhook
```
