### ISSUE TITLE
Building a custom template

### ISSUE THREAD

**Issue by callahan22** [prometheus-msteams/prometheus-msteams#251]
I'm really struggling to understand the code structure of the default template. I built a docker stack like this a my last company but it was some time ago and my notes from then are not helping much!

I remember this being the stumbling block last time too. Are there any detailed guides on how the structure of the default template is built? At the moment, I feel like I'm just pasting blocks of text into the config and crossing my fingers!
For example, I want to strip out or replace the names of some of what is being reported, like instance for example or "os".

So I took the default template and changed it to look like that below. I wanted to test it to see if I could take the value of the alert.label.severity which is being pulled from the alerts.yml file and rename the field using an uppercase "S" as despite the alerts.yml being configured as shown below, the field names are all getting dropped to lowercase.

```
# Alert when an internal website is down.
  - name: 'Client website certificate expiring in less than 2 weeks'
    rules:
    - alert: 'Client website certificate expiring in less than 2 weeks'
      expr: probe_ssl_earliest_cert_expiry{job="Websites"} -time() < 604800
      for: 10s
      labels:
        Severity: Warning
      annotations:
        url: "https://grafana.mydomain.com"
```

I'm also trying to take the instance field which is coming from Prometheus and use it in a field called URL.

```
{{ define "teams.card" }}
{
  "@type": "MessageCard",
  "@context": "http://schema.org/extensions",
  "themeColor": "{{- if eq .Status "resolved" -}}2DC72D
                 {{- else if eq .Status "firing" -}}
                    {{- if eq .CommonLabels.severity "critical" -}}8C1A1A
                    {{- else if eq .CommonLabels.severity "warning" -}}FFA500
                    {{- else -}}808080{{- end -}}
                 {{- else -}}808080{{- end -}}",
  "summary": "{{ .CommonAnnotations.summary }}",
  "title": "Prometheus Alert ({{ .Status }})",
  "sections": [ {{$externalUrl := .ExternalURL}}
  {{- range $index, $alert := .Alerts }}{{- if $index }},{{- end }}
    {
      "activityTitle": "[{{ $alert.Annotations.description }}]({{ $externalUrl }})",
      "facts": [
       {{/* Take the value of $alert.Labels.severity from alert-rules.yml and add it to an alert
       field labelled "Severity" */}}
       {
         "name": "Severity:",
         "value": "{{ $alert.labels.severity }}"
       },
        {
          "name": "URL",
          "value": "{{ $alert.CommonAnnotations.instance }}"
        }
      ],
      "markdown": true
    }
    {{- end }}
  ]
}
{{ end }}
```

The end result is the following error:

`
{"caller":"transport.go:76","err":"failed to parse webhook message: failed to template alerts: template: default.tmpl:22:28: executing \"teams.card\" at <$alert.labels.Severity>: can't evaluate field labels in type template.Alert","ts":"2022-05-15T19:46:36.003716025Z"}
`

I'm also taking a complete guess on:

`$alert.CommonAnnotations.instance`

as I'm assuming all fields that are retuned from Prometheus fall into the CommonAnnotations category(?).

There are a host of other things I've tried but without fully understanding what most of that template is doing, I'm struggling! For another example, where is this $ExternalURL defined?!

`"sections": [ {{$externalUrl := .ExternalURL}}`

I feel like I'm missing something obvious but the longer I stay at it, the less it makes sense so if anyone can point me to a detailed guide on writing these templates, I'd appreciate it.
