### ISSUE TITLE
[BUG] Enabling `-validate-webhook-url` results in error

### ISSUE THREAD

**Issue by bodgit** [prometheus-msteams/prometheus-msteams#255]
**Describe the bug**
Assuming the README example of configuring the connectors like so:
```yaml
connectors:
# in alertmanager, this will be used as http://prometheus-msteams:2000/bar
- bar: https://outlook.office.com/webhook/xxxx/xxxx
# in alertmanager, this will be used as http://prometheus-msteams:2000/foo
- foo: https://outlook.office.com/webhook/xxxx/xxxx
```
When passing the `-validate-webhook-url` argument, this results in the following error:
```
the webhook_url must start with 'https://'. url: 'bar'
```
or
```
the webhook_url must start with 'https://'. url: 'foo'
```
It looks like the bug is at https://github.com/prometheus-msteams/prometheus-msteams/blob/cca313db83adbb88c548199732e8bfe0fac0775e/cmd/server/main.go#L256-L257

Surely `validateWebhook()` should be passed `webhook` rather than `uri`?

**Version**
1.5.0

**To Reproduce**
Configure some connectors and pass `-validate-webhook-url` in the args.

**Expected behavior**
Nothing 😄, assuming the webhook URL is in the expected format.

**Additional context**
Introduced by #187
