### ISSUE TITLE
Add support of annotations for kuberntes Service

### ISSUE THREAD

**Issue by antonioua** [prometheus-msteams/prometheus-msteams#275]
We have a case when we need to expose Service through Azure Load Balancer. 
Currently we are using kustomize and helm post-render to achieve this but it'll be nice to have this configurable in `values.yaml`.

Proposal config entry in values.yaml:
```yaml
service:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
```

Resulting Service manifest:
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  name: prometheus-msteams
```
