### ISSUE TITLE
[FEATURE]In case of kubernetes chart would be very good to have a possibility to pass webhook urls as external secret

### ISSUE THREAD

**Issue by alexandergoncharovaspecta** [prometheus-msteams/prometheus-msteams#282]
I would like to use connectorsWithCustomTemplates to create different endpoints and templates for different scenarios. All works perfectly but I need a way to pass webhook_url by reading from external secrets.

**Comment by rufreakde** [comment]
+ bumb this as it is a critical feature for declarative setups with tools like argocd and bitnami sealedsecrets.

**Comment by alexandergoncharovaspecta** [comment]
I use external secret operator and sure does not store sensitive data in repo. So I can keep webhook_url in external secret which will be converted in secret. But there is not way how to pass it in connectorsWithCustomTemplates. That was my question.
Thanks.

**Comment by clive-jevons** [comment]
I've submitted PR https://github.com/prometheus-msteams/prometheus-msteams/pull/332 which should go a ways towards helping here, if accepted. We have a similar problem, where we want to provide the connectors config in the form of a k8s secret and need a way to get the helm chart to render a Deployment which uses that secret rather than the default config map.

**Comment by stand-sure** [comment]
> > I use external secret operator and sure does not store sensitive data in repo. So I can keep webhook_url in external secret which will be converted in secret. But there is not way how to pass it in connectorsWithCustomTemplates. That was my question. Thanks.
> 
> You can kind of already do this with having your connectors config in a secret
> ```yaml
> connectors:
> - high_priority_channel: "https://outlook.office.com/webhook/xxxx/aaa/bbb"
> - low_priority_channel: "https://outlook.office.com/webhook/xxxx/aaa/ccc"
> ```
>  and mounting it as a volume to `/etc/config/connectors.yaml` or specifying different path via env var `CONFIG_FILE`

This is not correct

The configmap mounted by the chart at /etc/config is already mounting the file connectors.yaml and it seems the directory isn't preexisting. The additional mount attempt will fail with a cryptic message stating that the attempted subPath mount isn't targeting a directory.

An attempt to just do a second mount to overwrite the first will fail validation.

**Comment by stand-sure** [comment]
you can, however, mount **somewhere else** and then use it

helm value overrides example

```yaml  
extraConfigmapMounts:
  - name: connectors-volume
    secret:
      secretName: prometheus-msteams-connectors

extraVolumeMounts:
  - name: connectors-volume
    mountPath: /etc/config2/connectors.yaml
    subPath: connectors.yaml
    readOnly: true

container:
  additionalArgs:
    - --config-file=/etc/config2/connectors.yaml
   
```
