### ISSUE TITLE
[BUG] Give up the way to run "prometheus-msteams" in docker

### ISSUE THREAD

**Issue by ozbillwang** [prometheus-msteams/prometheus-msteams#323]
**Describe the bug**
Spend so much time,  to run `prometheus-msteams` in docker, and always get the error `i/o timeout`

**Version**
1.5.2

**To Reproduce**

run with docker compose
```
version: '3.8'

services:
  prom2teams:
    image: quay.io/prometheusmsteams/prometheus-msteams
    restart: always
    environment:
            TEAMS_INCOMING_WEBHOOK_URL: "<webhook_url>"
            TEAMS_REQUEST_URI: "alertmanager"

    ports:
            - 2000:2000
```                  
**Expected behavior**

```
2023/05/17 13:45:38 [ERR] POST https://<webhook_url> request failed: Post "https://<webhook_url>": dial tcp 52.98.0.146:443: i/o timeout
```
**Screenshots**

**Additional context**
