### ISSUE TITLE
Kustomize deployment: line 11: mapping key "release" already defined at line 10

### ISSUE THREAD

**Issue by Sispheor** [prometheus-msteams/prometheus-msteams#355]
**Describe the bug**
Trying to deploy msteams via helm/kustomize

**Version**
helm app version: 1.3.4
docker image: 1.5.2

**To Reproduce**

Kustolization.yml:
```yaml
generators:
  - prom-helm-chart.yaml
  - msteams-helm-chart.yaml

resources:
  - namespace.yaml
  - node_exporter.yml
  - scrape-with-secrets.yml

namespace: prometheus
```

msteams-helm-chart.yaml:
```yaml
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: prometheus-msteams
name: prometheus-msteams
namespace: prometheus
version: 1.3.4
releaseName: prometheus-msteams
repo: https://prometheus-msteams.github.io/prometheus-msteams/
valuesFile: msteams-values.yaml
includeCrds: true
```

values:
```yml
replicaCount: 1
image:
  repository: quay.io/prometheusmsteams/prometheus-msteams
  tag: v1.5.2

connectors:
  - bar: https://outlook.office.com/webhook/xxxx/xxxx

# Enable metrics for prometheus operator
metrics:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: prometheus # change this accordingly
    scrapeInterval: 30s
```

Run:
```
kustomize build --enable-helm apps/prometheus
```

Output:
```
Error: map[string]interface {}(nil): yaml: unmarshal errors:
  line 11: mapping key "release" already defined at line 10
```

**Expected behavior**
I expect the deployment to be performed by helm.
